// src/constants/statesAndCities.js

export const statesAndCities = {
  Maharashtra: [
    "Mumbai",
    "Pune",
    "Nagpur",
    "Thane",
    "Nashik",
    "Solapur",
    "Pimpri-Chinchwad",
    "Vasai-Virar",
  ],
  Gujarat: [
    "Ahmedabad",
    "Surat",
    "Vadodara",
    "Rajkot",
    "Bhavnagar",
    "Jamnagar",
  ],
  Karnataka: ["Bangalore", "Mysore", "Mangalore", "Hubli"],
  Delhi: ["Delhi"],
  "Tamil Nadu": ["Chennai", "Coimbatore", "Madurai"],
  "Uttar Pradesh": [
    "Lucknow",
    "Kanpur",
    "Agra",
    "Varanasi",
    "Ghaziabad",
    "Meerut",
    "Allahabad",
  ],
  Rajasthan: ["Jaipur", "Jodhpur", "Kota", "Udaipur"],
  "West Bengal": ["Kolkata", "Howrah"],
  Haryana: ["Faridabad"],
  Punjab: ["Ludhiana", "Amritsar"],
  Bihar: ["Patna"],
  Jharkhand: ["Ranchi", "Dhanbad"],
  "Andhra Pradesh": ["Visakhapatnam", "Vijayawada"],
  Chhattisgarh: ["Raipur"],
  "Himachal Pradesh": ["Shimla"],
  Guwahati: ["Guwahati"],
  Chandigarh: ["Chandigarh"],
};

export const stateSelectionOptions = [
  { value: "Andhra Pradesh", label: "[AP] - Andhra Pradesh" },
  { value: "Arunachal Pradesh", label: "[AR] - Arunachal Pradesh" },
  { value: "Assam", label: "[AS] - Assam" },
  { value: "Bihar", label: "[BR] - Bihar" },
  { value: "Chhattisgarh", label: "[CG] - Chhattisgarh" },
  { value: "Goa", label: "[GA] - Goa" },
  { value: "Gujarat", label: "[GJ] - Gujarat" },
  { value: "Haryana", label: "[HR] - Haryana" },
  { value: "Himachal Pradesh", label: "[HP] - Himachal Pradesh" },
  { value: "Jammu and Kashmir", label: "[JK] - Jammu and Kashmir" },
  { value: "Jharkhand", label: "[JH] - Jharkhand" },
  { value: "Karnataka", label: "[KA] - Karnataka" },
  { value: "Kerala", label: "[KL] - Kerala" },
  { value: "Madhya Pradesh", label: "[MP] - Madhya Pradesh" },
  { value: "Maharashtra", label: "[MH] - Maharashtra" },
  { value: "Manipur", label: "[MN] - Manipur" },
  { value: "Meghalaya", label: "[ML] - Meghalaya" },
  { value: "Mizoram", label: "[MZ] - Mizoram" },
  { value: "Nagaland", label: "[NL] - Nagaland" },
  { value: "Odisha", label: "[OD] - Odisha" },
  { value: "Punjab", label: "[PB] - Punjab" },
  { value: "Rajasthan", label: "[RJ] - Rajasthan" },
  { value: "Sikkim", label: "[SK] - Sikkim" },
  { value: "Tamil Nadu", label: "[TN] - Tamil Nadu" },
  { value: "Telangana", label: "[TG] - Telangana" },
  { value: "Tripura", label: "[TR] - Tripura" },
  { value: "Uttar Pradesh", label: "[UP] - Uttar Pradesh" },
  { value: "Uttarakhand", label: "[UK] - Uttarakhand" },
  { value: "West Bengal", label: "[WB] - West Bengal" },
  {
    value: "Andaman and Nicobar Islands",
    label: "[AN] - Andaman and Nicobar Islands",
  },
  { value: "Chandigarh", label: "[CH] - Chandigarh" },
  {
    value: "Dadra and Nagar Haveli",
    label: "[DNH] - Dadra and Nagar Haveli",
  },
  { value: "Daman and Diu", label: "[DD] - Daman and Diu" },
  { value: "Delhi", label: "[DL] - Delhi" },
  { value: "Lakshadweep", label: "[LD] - Lakshadweep" },
  { value: "Puducherry", label: "[PY] - Puducherry" },
];
